<?php

declare(strict_types=1);

use App\Http\Controllers\Admin\ApplicationsExportController;
use App\Http\Controllers\Admin\ChatLogController;
use App\Http\Controllers\Admin\CompanyController;
use App\Http\Controllers\Admin\CourseController;
use App\Http\Controllers\Admin\CourseImportController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\DomainController;
use App\Http\Controllers\Admin\DomainExportController;
use App\Http\Controllers\Admin\DomainImportController;
use App\Http\Controllers\Admin\DomainSearchController;
use App\Http\Controllers\Admin\EmployerVerifyController;
use App\Http\Controllers\Admin\FeedbackController;
use App\Http\Controllers\Admin\IndustriesImportController;
use App\Http\Controllers\Admin\IndustryController;
use App\Http\Controllers\Admin\JobController;
use App\Http\Controllers\Admin\JobReportExportController;
use App\Http\Controllers\Admin\JobTitlesImportController;
use App\Http\Controllers\Admin\JobVerifyController;
use App\Http\Controllers\Admin\LanguageController;
use App\Http\Controllers\Admin\LocationController;
use App\Http\Controllers\Admin\OpeningTitleController;
use App\Http\Controllers\Admin\RecruiterController;
use App\Http\Controllers\Admin\RecruiterExportController;
use App\Http\Controllers\Admin\Reports\JobController as ReportsJobController;
use App\Http\Controllers\Admin\Reports\StudentController as ReportsStudentController;
use App\Http\Controllers\Admin\SiteSettingController;
use App\Http\Controllers\Admin\SkillController;
use App\Http\Controllers\Admin\SkillExportController;
use App\Http\Controllers\Admin\SkillsImportController;
use App\Http\Controllers\Admin\StudentReportExportController;
use App\Http\Controllers\Admin\StudentVerificationController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\VerificationController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\StudentController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->name('admin.')->group(function (): void {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('/roles', RoleController::class);
    Route::resource('/job-titles', OpeningTitleController::class);
    Route::post('/job-titles/import', JobTitlesImportController::class);
    Route::get('/skills/export', SkillExportController::class);
    Route::resource('/skills', SkillController::class);
    Route::post('/skills/import', SkillsImportController::class);
    Route::resource('/users', UserController::class);
    Route::get('/recruiters/export', RecruiterExportController::class);
    Route::resource('/recruiters', RecruiterController::class);
    Route::get('/companies/export', [CompanyController::class, 'export']);
    Route::patch('/companies/{company}/status', [CompanyController::class, 'updateStatus'])->name('companies.updateStatus');
    Route::resource('/companies', CompanyController::class);
    Route::get('/students/export', [StudentController::class, 'export']);
    Route::resource('/students', StudentController::class);
    Route::patch('/students/{user}/status', [StudentController::class, 'updateStatus'])->name('students.updateStatus');
    Route::resource('/jobs', JobController::class);
    Route::get('/jobs/{job}/applications', [JobController::class, 'applications'])->name('jobs.applications.index');
    Route::post('/jobs/{job}/applications', [JobController::class, 'storeApplications'])->name('jobs.applications.store');
    Route::get('/employer/verify', [EmployerVerifyController::class, 'verify'])->name('employer.verify');
    Route::post('/employer/verify', [EmployerVerifyController::class, 'store'])->name('employer.verify.store');
    Route::get('/job/verify', [JobVerifyController::class, 'verify'])->name('job.verify');
    Route::post('/job/verify/{opening}', [JobVerifyController::class, 'store'])->name('job.verify.store');
    Route::get('/pending-verifications', [VerificationController::class, 'index']);
    Route::resource('/industries', IndustryController::class);
    Route::post('/industries/import', IndustriesImportController::class);
    Route::resource('/locations', LocationController::class);
    Route::resource('/languages', LanguageController::class);
    Route::get('/site-settings', [SiteSettingController::class, 'index'])->name('site.settings');
    Route::post('/site-settings', [SiteSettingController::class, 'store'])->name('site.settings.store');
    Route::get('/students/verify/{student}', [StudentVerificationController::class, 'show'])->name('students.verify');
    Route::post('/students/verify/{student}', [StudentVerificationController::class, 'verify'])->name('students.verify.approve');
    Route::delete('/students/reject/{student}', [StudentVerificationController::class, 'reject'])->name('students.verify.reject');
    Route::get('/feedback', [FeedbackController::class, 'index'])->name('feedback.index');
    Route::get('/feedback/{feedback}', [FeedbackController::class, 'show'])->name('feedback.show');
    Route::get('/jobs/{job}/applications/export', ApplicationsExportController::class)->name('jobs.applications.export');
    Route::get('/chat-logs', ChatLogController::class)->name('chat-logs');
    Route::resource('/courses', CourseController::class);
    Route::post('/courses/import', CourseImportController::class);
    Route::get('/jobs/{job}/applications/resumes/download-selected', [JobController::class, 'downloadSelectedResumes'])->name('jobs.applications.resumes.download-selected');
    Route::prefix('/reports')->name('reports.')->group(function (): void {
        Route::get('/students/export', StudentReportExportController::class);
        Route::get('/students', [ReportsStudentController::class, 'index'])->name('students.index');
        Route::get('/jobs/export', JobReportExportController::class);
        Route::get('/jobs', [ReportsJobController::class, 'index'])->name('jobs.index');
    });
    Route::get('/domains/search', DomainSearchController::class);
    Route::get('/domains/export', DomainExportController::class);
    Route::post('/domains/import', DomainImportController::class);
    Route::resource('/domains', DomainController::class);
    Route::get('/domains/{domain}/skills', [DomainController::class, 'skills']);
});
