name: Deploy website on push

on:
  push:
    branches:
      - deploy

jobs:
  admin-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Use Node.js # installs the specified version of nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Use PHP # installs the specified version of php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'

    - name: Installing Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/compose

    - name: Installing PHP dependencies
      run: composer install

    - name: Installing Node dependencies
      run: |
        npm i
        npm run build

    - name: Deploying project # copy files to specified FTP directory
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        exclude: |
          **/.git*
          **/.git*/**
          **/.env.example
          **/.editorconfig